name: Build & publish to registry 

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    container: ghcr.io/viam-modules/raspberry-pi:arm64
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: viamrobotics/build-action@v1
      with:
        version: ${{ github.ref_name }}
        ref: ${{ github.sha }}
        key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
        key-value: ${{ secrets.VIAM_DEV_API_KEY }}
        